import Image from 'next/image'

export const metadata = {
  title: 'WikiRocket',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      
    </main>
  )
}
